# initialize variables
load('~/Dropbox/Research_projects/AA_CAMELS_CL/Updating_CAMELScl/v2021/processed_data/v2021_12/camels_v2021_attributes.RData')

data_platform_mon = data.frame(gauge_id=numeric(0),
                               gauge_name=numeric(0),
                               area_km2=numeric(0),
                               date=numeric(0),
                               pr_mm_mon=numeric(0),
                               et_mm_mon=numeric(0),
                               tmin_C_mon=numeric(0),
                               tmax_C_mon=numeric(0),
                               tavg_C_mon=numeric(0),
                               pet_mm_mon=numeric(0),
                               qobs_m3s=numeric(0),
                               qobs_mm_mon=numeric(0),
                               qsim_m3s=numeric(0),
                               qsim_mm_mon=numeric(0),
                               sim_short_name=numeric(0),
                               sim_pr_name=numeric(0),
                               sim_pet_name=numeric(0),
                               sim_txn_name=numeric(0),
                               sim_lai_name=numeric(0)
)

data_platform_yr  = data.frame(gauge_id=numeric(0),
                               gauge_name=numeric(0),
                               area_km2=numeric(0),
                               date=numeric(0),
                               pr_mm_yr=numeric(0),
                               et_mm_yr=numeric(0),
                               tmin_C_yr=numeric(0),
                               tmax_C_yr=numeric(0),
                               tavg_C_yr=numeric(0),
                               pet_mm_yr=numeric(0),
                               qobs_m3s_yr=numeric(0),
                               qobs_mm_yr=numeric(0),
                               qsim_m3s_yr=numeric(0),
                               qsim_mm_yr=numeric(0),
                               sim_short_name=numeric(0),
                               sim_pr_name=numeric(0),
                               sim_pet_name=numeric(0),
                               sim_txn_name=numeric(0),
                               sim_lai_name=numeric(0)
)

data_platform_mon_LTM = data.frame(gauge_id=numeric(0),
                                   gauge_name=numeric(0),
                                   area_km2=numeric(0),
                                   date=numeric(0),
                                   
                                   sim_short_name=numeric(0),
                                   sim_pr_name=numeric(0),
                                   sim_pet_name=numeric(0),
                                   sim_txn_name=numeric(0),
                                   sim_lai_name=numeric(0),
                                   
                                   pr_mm_mon_LTM_1960_2020=numeric(0),
                                   et_mm_mon_LTM_1960_2020=numeric(0),
                                   tmin_C_mon_LTM_1960_2020=numeric(0),
                                   tmax_C_mon_LTM_1960_2020=numeric(0),
                                   tavg_C_mon_LTM_1960_2020=numeric(0),
                                   pet_mm_mon_LTM_1960_2020=numeric(0),
                                   qobs_m3s_mon_LTM_1960_2020=numeric(0),
                                   qobs_mm_mon_LTM_1960_2020=numeric(0),
                                   qsim_m3s_mon_LTM_1960_2020=numeric(0),
                                   qsim_mm_mon_LTM_1960_2020=numeric(0),
                                   
                                   pr_mm_mon_LTM_1960_1990=numeric(0),
                                   et_mm_mon_LTM_1960_1990=numeric(0),
                                   tmin_C_mon_LTM_1960_1990=numeric(0),
                                   tmax_C_mon_LTM_1960_1990=numeric(0),
                                   tavg_C_mon_LTM_1960_1990=numeric(0),
                                   pet_mm_mon_LTM_1960_1990=numeric(0),
                                   qobs_m3s_mon_LTM_1960_1990=numeric(0),
                                   qobs_mm_mon_LTM_1960_1990=numeric(0),
                                   qsim_m3s_mon_LTM_1960_1990=numeric(0),
                                   qsim_mm_mon_LTM_1960_1990=numeric(0),
                                   
                                   pr_mm_mon_LTM_1990_2020=numeric(0),
                                   et_mm_mon_LTM_1990_2020=numeric(0),
                                   tmin_C_mon_LTM_1990_2020=numeric(0),
                                   tmax_C_mon_LTM_1990_2020=numeric(0),
                                   tavg_C_mon_LTM_1990_2020=numeric(0),
                                   pet_mm_mon_LTM_1990_2020=numeric(0),
                                   qobs_m3s_mon_LTM_1990_2020=numeric(0),
                                   qobs_mm_mon_LTM_1990_2020=numeric(0),
                                   qsim_m3s_mon_LTM_1990_2020=numeric(0),
                                   qsim_mm_mon_LTM_1990_2020=numeric(0),
                                   
                                   pr_mm_mon_LTM_2040_2070=numeric(0),
                                   et_mm_mon_LTM_2040_2070=numeric(0),
                                   tmin_C_mon_LTM_2040_2070=numeric(0),
                                   tmax_C_mon_LTM_2040_2070=numeric(0),
                                   tavg_C_mon_LTM_2040_2070=numeric(0),
                                   pet_mm_mon_LTM_2040_2070=numeric(0),
                                   qobs_m3s_mon_LTM_2040_2070=numeric(0),
                                   qobs_mm_mon_LTM_2040_2070=numeric(0),
                                   qsim_m3s_mon_LTM_2040_2070=numeric(0),
                                   qsim_mm_mon_LTM_2040_2070=numeric(0),
                                   
                                   pr_mm_mon_LTM_2070_2100=numeric(0),
                                   et_mm_mon_LTM_2070_2100=numeric(0),
                                   tmin_C_mon_LTM_2070_2100=numeric(0),
                                   tmax_C_mon_LTM_2070_2100=numeric(0),
                                   tavg_C_mon_LTM_2070_2100=numeric(0),
                                   pet_mm_mon_LTM_2070_2100=numeric(0),
                                   qobs_m3s_mon_LTM_2070_2100=numeric(0),
                                   qobs_mm_mon_LTM_2070_2100=numeric(0),
                                   qsim_m3s_mon_LTM_2070_2100=numeric(0),
                                   qsim_mm_mon_LTM_2070_2100=numeric(0)
                                   
)